run:
  go: "1.23"
  tests: false
issues:
  exclude-dirs:
    - temp
    - test
    - cmd
    - scratch
    - gen
    - mocks
  exclude-files:
    - ".*_gen.go$"
    - ".*.pb.go$"
    - "mock_*.go$"
linters:
  enable-all: true
  disable:
    - contextcheck
    - depguard
    - dupl
    - exhaustruct
    - exportloopref
    - funlen
    - gci # (using custom prefix and don't feel like configuring this to do it also)
    - gochecknoglobals
    - ireturn
    - lll
    - nilnil
    - nlreturn
    - tagalign
    - tagliatelle
    - varnamelen
    - wrapcheck
linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  godox:
    keywords:
      - HACK
      - TEMP
      - FIX
      - FIXME
  cyclop:
    max-complexity: 15
  nestif:
    # minimal complexity of if statements to report, 5 by default
    min-complexity: 7
  revive:
    # see https://github.com/mgechev/revive#available-rules for details.
    ignore-generated-header: true
    # Using an opt-in approach since it is impossible to
    # disable specific rules otherwise. Starting with recommended set.
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
