language: go
go_import_path: github.com/gofoji/pgtree
go:
  - 1.14.x

cache:
  directories:
    - $GOPATH/pkg/mod

jobs:
  include:
    - stage: "Compile"
      name: "Compile Packages and Dependencies"
      script: go build
    - stage: "Tests"
      name: "Unit Tests"
      script: go test ./... -coverprofile=coverage.txt -covermode=count
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: "Code Quality"
      name: "Code Quality Analysis"
      before_script:
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.31.0
      script: ./bin/golangci-lint run