// Code generated by foji 0.3, template: foji/node_walk.go.tpl; DO NOT EDIT.

package pgtree

type Visitor func(node Node, stack []Node, v Visitor) Visitor

func WalkList(list Nodes, stack []Node, v Visitor) {
	for _, n := range list {
		Walk(n, stack, v)
	}
}

func Walk(node Node, stack []Node, v Visitor) {
	if node == nil || isNilValue(node) {
		return
	}

	if v = v(node, stack, v); v == nil {
		return
	}

	stack = append(stack, node)
	switch n := node.(type) {
	case *List:
		WalkList(n.Items, stack, v)
	case *OidList:
		WalkList(n.Items, stack, v)
	case *IntList:
		WalkList(n.Items, stack, v)
	case *Alias:
		WalkList(n.Colnames, stack, v)
	case *RangeVar:
		Walk(n.Alias, stack, v)
	case *TableFunc:
		WalkList(n.NsUris, stack, v)
		WalkList(n.NsNames, stack, v)
		Walk(n.Docexpr, stack, v)
		Walk(n.Rowexpr, stack, v)
		WalkList(n.Colnames, stack, v)
		WalkList(n.Coltypes, stack, v)
		WalkList(n.Coltypmods, stack, v)
		WalkList(n.Colcollations, stack, v)
		WalkList(n.Colexprs, stack, v)
		WalkList(n.Coldefexprs, stack, v)
	case *Var:
		Walk(n.Xpr, stack, v)
	case *Param:
		Walk(n.Xpr, stack, v)
	case *Aggref:
		Walk(n.Xpr, stack, v)
		WalkList(n.Aggargtypes, stack, v)
		WalkList(n.Aggdirectargs, stack, v)
		WalkList(n.Args, stack, v)
		WalkList(n.Aggorder, stack, v)
		WalkList(n.Aggdistinct, stack, v)
		Walk(n.Aggfilter, stack, v)
	case *GroupingFunc:
		Walk(n.Xpr, stack, v)
		WalkList(n.Args, stack, v)
		WalkList(n.Refs, stack, v)
		WalkList(n.Cols, stack, v)
	case *WindowFunc:
		Walk(n.Xpr, stack, v)
		WalkList(n.Args, stack, v)
		Walk(n.Aggfilter, stack, v)
	case *SubscriptingRef:
		Walk(n.Xpr, stack, v)
		WalkList(n.Refupperindexpr, stack, v)
		WalkList(n.Reflowerindexpr, stack, v)
		Walk(n.Refexpr, stack, v)
		Walk(n.Refassgnexpr, stack, v)
	case *FuncExpr:
		Walk(n.Xpr, stack, v)
		WalkList(n.Args, stack, v)
	case *NamedArgExpr:
		Walk(n.Xpr, stack, v)
		Walk(n.Arg, stack, v)
	case *OpExpr:
		Walk(n.Xpr, stack, v)
		WalkList(n.Args, stack, v)
	case *DistinctExpr:
		Walk(n.Xpr, stack, v)
		WalkList(n.Args, stack, v)
	case *NullIfExpr:
		Walk(n.Xpr, stack, v)
		WalkList(n.Args, stack, v)
	case *ScalarArrayOpExpr:
		Walk(n.Xpr, stack, v)
		WalkList(n.Args, stack, v)
	case *BoolExpr:
		Walk(n.Xpr, stack, v)
		WalkList(n.Args, stack, v)
	case *SubLink:
		Walk(n.Xpr, stack, v)
		Walk(n.Testexpr, stack, v)
		WalkList(n.OperName, stack, v)
		Walk(n.Subselect, stack, v)
	case *SubPlan:
		Walk(n.Xpr, stack, v)
		Walk(n.Testexpr, stack, v)
		WalkList(n.ParamIds, stack, v)
		WalkList(n.SetParam, stack, v)
		WalkList(n.ParParam, stack, v)
		WalkList(n.Args, stack, v)
	case *AlternativeSubPlan:
		Walk(n.Xpr, stack, v)
		WalkList(n.Subplans, stack, v)
	case *FieldSelect:
		Walk(n.Xpr, stack, v)
		Walk(n.Arg, stack, v)
	case *FieldStore:
		Walk(n.Xpr, stack, v)
		Walk(n.Arg, stack, v)
		WalkList(n.Newvals, stack, v)
		WalkList(n.Fieldnums, stack, v)
	case *RelabelType:
		Walk(n.Xpr, stack, v)
		Walk(n.Arg, stack, v)
	case *CoerceViaIo:
		Walk(n.Xpr, stack, v)
		Walk(n.Arg, stack, v)
	case *ArrayCoerceExpr:
		Walk(n.Xpr, stack, v)
		Walk(n.Arg, stack, v)
		Walk(n.Elemexpr, stack, v)
	case *ConvertRowtypeExpr:
		Walk(n.Xpr, stack, v)
		Walk(n.Arg, stack, v)
	case *CollateExpr:
		Walk(n.Xpr, stack, v)
		Walk(n.Arg, stack, v)
	case *CaseExpr:
		Walk(n.Xpr, stack, v)
		Walk(n.Arg, stack, v)
		WalkList(n.Args, stack, v)
		Walk(n.Defresult, stack, v)
	case *CaseWhen:
		Walk(n.Xpr, stack, v)
		Walk(n.Expr, stack, v)
		Walk(n.Result, stack, v)
	case *CaseTestExpr:
		Walk(n.Xpr, stack, v)
	case *ArrayExpr:
		Walk(n.Xpr, stack, v)
		WalkList(n.Elements, stack, v)
	case *RowExpr:
		Walk(n.Xpr, stack, v)
		WalkList(n.Args, stack, v)
		WalkList(n.Colnames, stack, v)
	case *RowCompareExpr:
		Walk(n.Xpr, stack, v)
		WalkList(n.Opnos, stack, v)
		WalkList(n.Opfamilies, stack, v)
		WalkList(n.Inputcollids, stack, v)
		WalkList(n.Largs, stack, v)
		WalkList(n.Rargs, stack, v)
	case *CoalesceExpr:
		Walk(n.Xpr, stack, v)
		WalkList(n.Args, stack, v)
	case *MinMaxExpr:
		Walk(n.Xpr, stack, v)
		WalkList(n.Args, stack, v)
	case *SqlvalueFunction:
		Walk(n.Xpr, stack, v)
	case *XmlExpr:
		Walk(n.Xpr, stack, v)
		WalkList(n.NamedArgs, stack, v)
		WalkList(n.ArgNames, stack, v)
		WalkList(n.Args, stack, v)
	case *NullTest:
		Walk(n.Xpr, stack, v)
		Walk(n.Arg, stack, v)
	case *BooleanTest:
		Walk(n.Xpr, stack, v)
		Walk(n.Arg, stack, v)
	case *CoerceToDomain:
		Walk(n.Xpr, stack, v)
		Walk(n.Arg, stack, v)
	case *CoerceToDomainValue:
		Walk(n.Xpr, stack, v)
	case *SetToDefault:
		Walk(n.Xpr, stack, v)
	case *CurrentOfExpr:
		Walk(n.Xpr, stack, v)
	case *NextValueExpr:
		Walk(n.Xpr, stack, v)
	case *InferenceElem:
		Walk(n.Xpr, stack, v)
		Walk(n.Expr, stack, v)
	case *TargetEntry:
		Walk(n.Xpr, stack, v)
		Walk(n.Expr, stack, v)
	case *JoinExpr:
		Walk(n.Larg, stack, v)
		Walk(n.Rarg, stack, v)
		WalkList(n.UsingClause, stack, v)
		Walk(n.Quals, stack, v)
		Walk(n.Alias, stack, v)
	case *FromExpr:
		WalkList(n.Fromlist, stack, v)
		Walk(n.Quals, stack, v)
	case *OnConflictExpr:
		WalkList(n.ArbiterElems, stack, v)
		Walk(n.ArbiterWhere, stack, v)
		WalkList(n.OnConflictSet, stack, v)
		Walk(n.OnConflictWhere, stack, v)
		WalkList(n.ExclRelTlist, stack, v)
	case *IntoClause:
		Walk(n.Rel, stack, v)
		WalkList(n.ColNames, stack, v)
		WalkList(n.Options, stack, v)
		Walk(n.ViewQuery, stack, v)
	case *RawStmt:
		Walk(n.Stmt, stack, v)
	case *Query:
		Walk(n.UtilityStmt, stack, v)
		WalkList(n.CteList, stack, v)
		WalkList(n.Rtable, stack, v)
		Walk(n.Jointree, stack, v)
		WalkList(n.TargetList, stack, v)
		Walk(n.OnConflict, stack, v)
		WalkList(n.ReturningList, stack, v)
		WalkList(n.GroupClause, stack, v)
		WalkList(n.GroupingSets, stack, v)
		Walk(n.HavingQual, stack, v)
		WalkList(n.WindowClause, stack, v)
		WalkList(n.DistinctClause, stack, v)
		WalkList(n.SortClause, stack, v)
		Walk(n.LimitOffset, stack, v)
		Walk(n.LimitCount, stack, v)
		WalkList(n.RowMarks, stack, v)
		Walk(n.SetOperations, stack, v)
		WalkList(n.ConstraintDeps, stack, v)
		WalkList(n.WithCheckOptions, stack, v)
	case *InsertStmt:
		Walk(n.Relation, stack, v)
		WalkList(n.Cols, stack, v)
		Walk(n.SelectStmt, stack, v)
		Walk(n.OnConflictClause, stack, v)
		WalkList(n.ReturningList, stack, v)
		Walk(n.WithClause, stack, v)
	case *DeleteStmt:
		Walk(n.Relation, stack, v)
		WalkList(n.UsingClause, stack, v)
		Walk(n.WhereClause, stack, v)
		WalkList(n.ReturningList, stack, v)
		Walk(n.WithClause, stack, v)
	case *UpdateStmt:
		Walk(n.Relation, stack, v)
		WalkList(n.TargetList, stack, v)
		Walk(n.WhereClause, stack, v)
		WalkList(n.FromClause, stack, v)
		WalkList(n.ReturningList, stack, v)
		Walk(n.WithClause, stack, v)
	case *SelectStmt:
		WalkList(n.DistinctClause, stack, v)
		Walk(n.IntoClause, stack, v)
		WalkList(n.TargetList, stack, v)
		WalkList(n.FromClause, stack, v)
		Walk(n.WhereClause, stack, v)
		WalkList(n.GroupClause, stack, v)
		Walk(n.HavingClause, stack, v)
		WalkList(n.WindowClause, stack, v)
		WalkList(n.ValuesLists, stack, v)
		WalkList(n.SortClause, stack, v)
		Walk(n.LimitOffset, stack, v)
		Walk(n.LimitCount, stack, v)
		WalkList(n.LockingClause, stack, v)
		Walk(n.WithClause, stack, v)
		Walk(n.Larg, stack, v)
		Walk(n.Rarg, stack, v)
	case *AlterTableStmt:
		Walk(n.Relation, stack, v)
		WalkList(n.Cmds, stack, v)
	case *AlterTableCmd:
		Walk(n.Newowner, stack, v)
		Walk(n.Def, stack, v)
	case *AlterDomainStmt:
		WalkList(n.TypeName, stack, v)
		Walk(n.Def, stack, v)
	case *SetOperationStmt:
		Walk(n.Larg, stack, v)
		Walk(n.Rarg, stack, v)
		WalkList(n.ColTypes, stack, v)
		WalkList(n.ColTypmods, stack, v)
		WalkList(n.ColCollations, stack, v)
		WalkList(n.GroupClauses, stack, v)
	case *GrantStmt:
		WalkList(n.Objects, stack, v)
		WalkList(n.Privileges, stack, v)
		WalkList(n.Grantees, stack, v)
	case *GrantRoleStmt:
		WalkList(n.GrantedRoles, stack, v)
		WalkList(n.GranteeRoles, stack, v)
		Walk(n.Grantor, stack, v)
	case *AlterDefaultPrivilegesStmt:
		WalkList(n.Options, stack, v)
		Walk(n.Action, stack, v)
	case *ClusterStmt:
		Walk(n.Relation, stack, v)
	case *CopyStmt:
		Walk(n.Relation, stack, v)
		Walk(n.Query, stack, v)
		WalkList(n.Attlist, stack, v)
		WalkList(n.Options, stack, v)
		Walk(n.WhereClause, stack, v)
	case *CreateStmt:
		Walk(n.Relation, stack, v)
		WalkList(n.TableElts, stack, v)
		WalkList(n.InhRelations, stack, v)
		Walk(n.Partbound, stack, v)
		Walk(n.Partspec, stack, v)
		Walk(n.OfTypename, stack, v)
		WalkList(n.Constraints, stack, v)
		WalkList(n.Options, stack, v)
	case *DefineStmt:
		WalkList(n.Defnames, stack, v)
		WalkList(n.Args, stack, v)
		WalkList(n.Definition, stack, v)
	case *DropStmt:
		WalkList(n.Objects, stack, v)
	case *TruncateStmt:
		WalkList(n.Relations, stack, v)
	case *CommentStmt:
		Walk(n.Object, stack, v)
	case *IndexStmt:
		Walk(n.Relation, stack, v)
		WalkList(n.IndexParams, stack, v)
		WalkList(n.IndexIncludingParams, stack, v)
		WalkList(n.Options, stack, v)
		Walk(n.WhereClause, stack, v)
		WalkList(n.ExcludeOpNames, stack, v)
	case *CreateFunctionStmt:
		WalkList(n.Funcname, stack, v)
		WalkList(n.Parameters, stack, v)
		Walk(n.ReturnType, stack, v)
		WalkList(n.Options, stack, v)
	case *AlterFunctionStmt:
		Walk(n.Func, stack, v)
		WalkList(n.Actions, stack, v)
	case *DoStmt:
		WalkList(n.Args, stack, v)
	case *RenameStmt:
		Walk(n.Relation, stack, v)
		Walk(n.Object, stack, v)
	case *RuleStmt:
		Walk(n.Relation, stack, v)
		Walk(n.WhereClause, stack, v)
		WalkList(n.Actions, stack, v)
	case *TransactionStmt:
		WalkList(n.Options, stack, v)
	case *ViewStmt:
		Walk(n.View, stack, v)
		WalkList(n.Aliases, stack, v)
		Walk(n.Query, stack, v)
		WalkList(n.Options, stack, v)
	case *CreateDomainStmt:
		WalkList(n.Domainname, stack, v)
		Walk(n.TypeName, stack, v)
		Walk(n.CollClause, stack, v)
		WalkList(n.Constraints, stack, v)
	case *CreatedbStmt:
		WalkList(n.Options, stack, v)
	case *VacuumStmt:
		WalkList(n.Options, stack, v)
		WalkList(n.Rels, stack, v)
	case *ExplainStmt:
		Walk(n.Query, stack, v)
		WalkList(n.Options, stack, v)
	case *CreateTableAsStmt:
		Walk(n.Query, stack, v)
		Walk(n.Into, stack, v)
	case *CreateSeqStmt:
		Walk(n.Sequence, stack, v)
		WalkList(n.Options, stack, v)
	case *AlterSeqStmt:
		Walk(n.Sequence, stack, v)
		WalkList(n.Options, stack, v)
	case *VariableSetStmt:
		WalkList(n.Args, stack, v)
	case *CreateTrigStmt:
		Walk(n.Relation, stack, v)
		WalkList(n.Funcname, stack, v)
		WalkList(n.Args, stack, v)
		WalkList(n.Columns, stack, v)
		Walk(n.WhenClause, stack, v)
		WalkList(n.TransitionRels, stack, v)
		Walk(n.Constrrel, stack, v)
	case *CreatePlangStmt:
		WalkList(n.Plhandler, stack, v)
		WalkList(n.Plinline, stack, v)
		WalkList(n.Plvalidator, stack, v)
	case *CreateRoleStmt:
		WalkList(n.Options, stack, v)
	case *AlterRoleStmt:
		Walk(n.Role, stack, v)
		WalkList(n.Options, stack, v)
	case *DropRoleStmt:
		WalkList(n.Roles, stack, v)
	case *LockStmt:
		WalkList(n.Relations, stack, v)
	case *ConstraintsSetStmt:
		WalkList(n.Constraints, stack, v)
	case *ReindexStmt:
		Walk(n.Relation, stack, v)
	case *CreateSchemaStmt:
		Walk(n.Authrole, stack, v)
		WalkList(n.SchemaElts, stack, v)
	case *AlterDatabaseStmt:
		WalkList(n.Options, stack, v)
	case *AlterDatabaseSetStmt:
		Walk(n.Setstmt, stack, v)
	case *AlterRoleSetStmt:
		Walk(n.Role, stack, v)
		Walk(n.Setstmt, stack, v)
	case *CreateConversionStmt:
		WalkList(n.ConversionName, stack, v)
		WalkList(n.FuncName, stack, v)
	case *CreateCastStmt:
		Walk(n.Sourcetype, stack, v)
		Walk(n.Targettype, stack, v)
		Walk(n.Func, stack, v)
	case *CreateOpClassStmt:
		WalkList(n.Opclassname, stack, v)
		WalkList(n.Opfamilyname, stack, v)
		Walk(n.Datatype, stack, v)
		WalkList(n.Items, stack, v)
	case *CreateOpFamilyStmt:
		WalkList(n.Opfamilyname, stack, v)
	case *AlterOpFamilyStmt:
		WalkList(n.Opfamilyname, stack, v)
		WalkList(n.Items, stack, v)
	case *PrepareStmt:
		WalkList(n.Argtypes, stack, v)
		Walk(n.Query, stack, v)
	case *ExecuteStmt:
		WalkList(n.Params, stack, v)
	case *DeclareCursorStmt:
		Walk(n.Query, stack, v)
	case *CreateTableSpaceStmt:
		Walk(n.Owner, stack, v)
		WalkList(n.Options, stack, v)
	case *AlterObjectDependsStmt:
		Walk(n.Relation, stack, v)
		Walk(n.Object, stack, v)
		Walk(n.Extname, stack, v)
	case *AlterObjectSchemaStmt:
		Walk(n.Relation, stack, v)
		Walk(n.Object, stack, v)
	case *AlterOwnerStmt:
		Walk(n.Relation, stack, v)
		Walk(n.Object, stack, v)
		Walk(n.Newowner, stack, v)
	case *AlterOperatorStmt:
		Walk(n.Opername, stack, v)
		WalkList(n.Options, stack, v)
	case *DropOwnedStmt:
		WalkList(n.Roles, stack, v)
	case *ReassignOwnedStmt:
		WalkList(n.Roles, stack, v)
		Walk(n.Newrole, stack, v)
	case *CompositeTypeStmt:
		Walk(n.Typevar, stack, v)
		WalkList(n.Coldeflist, stack, v)
	case *CreateEnumStmt:
		WalkList(n.TypeName, stack, v)
		WalkList(n.Vals, stack, v)
	case *CreateRangeStmt:
		WalkList(n.TypeName, stack, v)
		WalkList(n.Params, stack, v)
	case *AlterEnumStmt:
		WalkList(n.TypeName, stack, v)
	case *AlterTsdictionaryStmt:
		WalkList(n.Dictname, stack, v)
		WalkList(n.Options, stack, v)
	case *AlterTsconfigurationStmt:
		WalkList(n.Cfgname, stack, v)
		WalkList(n.Tokentype, stack, v)
		WalkList(n.Dicts, stack, v)
	case *CreateFdwStmt:
		WalkList(n.FuncOptions, stack, v)
		WalkList(n.Options, stack, v)
	case *AlterFdwStmt:
		WalkList(n.FuncOptions, stack, v)
		WalkList(n.Options, stack, v)
	case *CreateForeignServerStmt:
		WalkList(n.Options, stack, v)
	case *AlterForeignServerStmt:
		WalkList(n.Options, stack, v)
	case *CreateUserMappingStmt:
		Walk(n.User, stack, v)
		WalkList(n.Options, stack, v)
	case *AlterUserMappingStmt:
		Walk(n.User, stack, v)
		WalkList(n.Options, stack, v)
	case *DropUserMappingStmt:
		Walk(n.User, stack, v)
	case *AlterTableSpaceOptionsStmt:
		WalkList(n.Options, stack, v)
	case *AlterTableMoveAllStmt:
		WalkList(n.Roles, stack, v)
	case *SecLabelStmt:
		Walk(n.Object, stack, v)
	case *CreateForeignTableStmt:
		Walk(n.Base, stack, v)
		WalkList(n.Options, stack, v)
	case *ImportForeignSchemaStmt:
		WalkList(n.TableList, stack, v)
		WalkList(n.Options, stack, v)
	case *CreateExtensionStmt:
		WalkList(n.Options, stack, v)
	case *AlterExtensionStmt:
		WalkList(n.Options, stack, v)
	case *AlterExtensionContentsStmt:
		Walk(n.Object, stack, v)
	case *CreateEventTrigStmt:
		WalkList(n.Whenclause, stack, v)
		WalkList(n.Funcname, stack, v)
	case *RefreshMatViewStmt:
		Walk(n.Relation, stack, v)
	case *AlterSystemStmt:
		Walk(n.Setstmt, stack, v)
	case *CreatePolicyStmt:
		Walk(n.Table, stack, v)
		WalkList(n.Roles, stack, v)
		Walk(n.Qual, stack, v)
		Walk(n.WithCheck, stack, v)
	case *AlterPolicyStmt:
		Walk(n.Table, stack, v)
		WalkList(n.Roles, stack, v)
		Walk(n.Qual, stack, v)
		Walk(n.WithCheck, stack, v)
	case *CreateTransformStmt:
		Walk(n.TypeName, stack, v)
		Walk(n.Fromsql, stack, v)
		Walk(n.Tosql, stack, v)
	case *CreateAmStmt:
		WalkList(n.HandlerName, stack, v)
	case *CreatePublicationStmt:
		WalkList(n.Options, stack, v)
		WalkList(n.Tables, stack, v)
	case *AlterPublicationStmt:
		WalkList(n.Options, stack, v)
		WalkList(n.Tables, stack, v)
	case *CreateSubscriptionStmt:
		WalkList(n.Publication, stack, v)
		WalkList(n.Options, stack, v)
	case *AlterSubscriptionStmt:
		WalkList(n.Publication, stack, v)
		WalkList(n.Options, stack, v)
	case *CreateStatsStmt:
		WalkList(n.Defnames, stack, v)
		WalkList(n.StatTypes, stack, v)
		WalkList(n.Exprs, stack, v)
		WalkList(n.Relations, stack, v)
	case *AlterCollationStmt:
		WalkList(n.Collname, stack, v)
	case *CallStmt:
		Walk(n.Funccall, stack, v)
		Walk(n.Funcexpr, stack, v)
	case *AExpr:
		WalkList(n.Name, stack, v)
		Walk(n.Lexpr, stack, v)
		Walk(n.Rexpr, stack, v)
	case *ColumnRef:
		WalkList(n.Fields, stack, v)
	case *AConst:
		Walk(n.Val, stack, v)
	case *FuncCall:
		WalkList(n.Funcname, stack, v)
		WalkList(n.Args, stack, v)
		WalkList(n.AggOrder, stack, v)
		Walk(n.AggFilter, stack, v)
		Walk(n.Over, stack, v)
	case *AIndices:
		Walk(n.Lidx, stack, v)
		Walk(n.Uidx, stack, v)
	case *AIndirection:
		Walk(n.Arg, stack, v)
		WalkList(n.Indirection, stack, v)
	case *AArrayExpr:
		WalkList(n.Elements, stack, v)
	case *ResTarget:
		WalkList(n.Indirection, stack, v)
		Walk(n.Val, stack, v)
	case *MultiAssignRef:
		Walk(n.Source, stack, v)
	case *TypeCast:
		Walk(n.Arg, stack, v)
		Walk(n.TypeName, stack, v)
	case *CollateClause:
		Walk(n.Arg, stack, v)
		WalkList(n.Collname, stack, v)
	case *SortBy:
		Walk(n.Node, stack, v)
		WalkList(n.UseOp, stack, v)
	case *WindowDef:
		WalkList(n.PartitionClause, stack, v)
		WalkList(n.OrderClause, stack, v)
		Walk(n.StartOffset, stack, v)
		Walk(n.EndOffset, stack, v)
	case *RangeSubselect:
		Walk(n.Subquery, stack, v)
		Walk(n.Alias, stack, v)
	case *RangeFunction:
		WalkList(n.Functions, stack, v)
		Walk(n.Alias, stack, v)
		WalkList(n.Coldeflist, stack, v)
	case *RangeTableSample:
		Walk(n.Relation, stack, v)
		WalkList(n.Method, stack, v)
		WalkList(n.Args, stack, v)
		Walk(n.Repeatable, stack, v)
	case *RangeTableFunc:
		Walk(n.Docexpr, stack, v)
		Walk(n.Rowexpr, stack, v)
		WalkList(n.Namespaces, stack, v)
		WalkList(n.Columns, stack, v)
		Walk(n.Alias, stack, v)
	case *RangeTableFuncCol:
		Walk(n.TypeName, stack, v)
		Walk(n.Colexpr, stack, v)
		Walk(n.Coldefexpr, stack, v)
	case *TypeName:
		WalkList(n.Names, stack, v)
		WalkList(n.Typmods, stack, v)
		WalkList(n.ArrayBounds, stack, v)
	case *ColumnDef:
		Walk(n.TypeName, stack, v)
		Walk(n.RawDefault, stack, v)
		Walk(n.CookedDefault, stack, v)
		Walk(n.IdentitySequence, stack, v)
		Walk(n.CollClause, stack, v)
		WalkList(n.Constraints, stack, v)
		WalkList(n.Fdwoptions, stack, v)
	case *IndexElem:
		Walk(n.Expr, stack, v)
		WalkList(n.Collation, stack, v)
		WalkList(n.Opclass, stack, v)
	case *Constraint:
		Walk(n.RawExpr, stack, v)
		WalkList(n.Keys, stack, v)
		WalkList(n.Including, stack, v)
		WalkList(n.Exclusions, stack, v)
		WalkList(n.Options, stack, v)
		Walk(n.WhereClause, stack, v)
		Walk(n.Pktable, stack, v)
		WalkList(n.FkAttrs, stack, v)
		WalkList(n.PkAttrs, stack, v)
		WalkList(n.OldConpfeqop, stack, v)
	case *DefElem:
		Walk(n.Arg, stack, v)
	case *RangeTblEntry:
		Walk(n.Tablesample, stack, v)
		Walk(n.Subquery, stack, v)
		WalkList(n.Joinaliasvars, stack, v)
		WalkList(n.Functions, stack, v)
		Walk(n.Tablefunc, stack, v)
		WalkList(n.ValuesLists, stack, v)
		WalkList(n.Coltypes, stack, v)
		WalkList(n.Coltypmods, stack, v)
		WalkList(n.Colcollations, stack, v)
		Walk(n.Alias, stack, v)
		Walk(n.Eref, stack, v)
		WalkList(n.SecurityQuals, stack, v)
	case *RangeTblFunction:
		Walk(n.Funcexpr, stack, v)
		WalkList(n.Funccolnames, stack, v)
		WalkList(n.Funccoltypes, stack, v)
		WalkList(n.Funccoltypmods, stack, v)
		WalkList(n.Funccolcollations, stack, v)
	case *TableSampleClause:
		WalkList(n.Args, stack, v)
		Walk(n.Repeatable, stack, v)
	case *WithCheckOption:
		Walk(n.Qual, stack, v)
	case *GroupingSet:
		WalkList(n.Content, stack, v)
	case *WindowClause:
		WalkList(n.PartitionClause, stack, v)
		WalkList(n.OrderClause, stack, v)
		Walk(n.StartOffset, stack, v)
		Walk(n.EndOffset, stack, v)
	case *ObjectWithArgs:
		WalkList(n.Objname, stack, v)
		WalkList(n.Objargs, stack, v)
	case *AccessPriv:
		WalkList(n.Cols, stack, v)
	case *CreateOpClassItem:
		Walk(n.Name, stack, v)
		WalkList(n.OrderFamily, stack, v)
		WalkList(n.ClassArgs, stack, v)
		Walk(n.Storedtype, stack, v)
	case *TableLikeClause:
		Walk(n.Relation, stack, v)
	case *FunctionParameter:
		Walk(n.ArgType, stack, v)
		Walk(n.Defexpr, stack, v)
	case *LockingClause:
		WalkList(n.LockedRels, stack, v)
	case *XmlSerialize:
		Walk(n.Expr, stack, v)
		Walk(n.TypeName, stack, v)
	case *WithClause:
		WalkList(n.Ctes, stack, v)
	case *InferClause:
		WalkList(n.IndexElems, stack, v)
		Walk(n.WhereClause, stack, v)
	case *OnConflictClause:
		Walk(n.Infer, stack, v)
		WalkList(n.TargetList, stack, v)
		Walk(n.WhereClause, stack, v)
	case *CommonTableExpr:
		WalkList(n.Aliascolnames, stack, v)
		Walk(n.Ctequery, stack, v)
		WalkList(n.Ctecolnames, stack, v)
		WalkList(n.Ctecoltypes, stack, v)
		WalkList(n.Ctecoltypmods, stack, v)
		WalkList(n.Ctecolcollations, stack, v)
	case *PartitionElem:
		Walk(n.Expr, stack, v)
		WalkList(n.Collation, stack, v)
		WalkList(n.Opclass, stack, v)
	case *PartitionSpec:
		WalkList(n.PartParams, stack, v)
	case *PartitionBoundSpec:
		WalkList(n.Listdatums, stack, v)
		WalkList(n.Lowerdatums, stack, v)
		WalkList(n.Upperdatums, stack, v)
	case *PartitionRangeDatum:
		Walk(n.Value, stack, v)
	case *PartitionCmd:
		Walk(n.Name, stack, v)
		Walk(n.Bound, stack, v)
	case *VacuumRelation:
		Walk(n.Relation, stack, v)
		WalkList(n.VaCols, stack, v)
	case *Root:
		Walk(n.Node, stack, v)
	case Nodes:
		WalkList(n, stack, v)
	}
}

type MutateFunc func(node *Node, stack []*Node, visitor MutateFunc) MutateFunc

func mutateList(list Nodes, stack []*Node, v MutateFunc) {
	for i := range list {
		mutate(&list[i], stack, v)
	}
}

func mutate(node *Node, stack []*Node, v MutateFunc) {
	var nodeWrapper Node
	if node == nil || isNilValue(*node) {
		return
	}

	if v = v(node, stack, v); v == nil {
		return
	}

	stack = append(stack, node)

	switch n := (*node).(type) {
	case *Integer:
	case *Float:
	case *String:
	case *BitString:
	case *Null:
	case *List:
		mutateList(n.Items, stack, v)
	case *OidList:
		mutateList(n.Items, stack, v)
	case *IntList:
		mutateList(n.Items, stack, v)
	case *Alias:
		mutateList(n.Colnames, stack, v)
	case *RangeVar:
		nodeWrapper = n.Alias
		mutate(&nodeWrapper, stack, v)
	case *TableFunc:
		mutateList(n.NsUris, stack, v)
		mutateList(n.NsNames, stack, v)
		mutate(&n.Docexpr, stack, v)
		mutate(&n.Rowexpr, stack, v)
		mutateList(n.Colnames, stack, v)
		mutateList(n.Coltypes, stack, v)
		mutateList(n.Coltypmods, stack, v)
		mutateList(n.Colcollations, stack, v)
		mutateList(n.Colexprs, stack, v)
		mutateList(n.Coldefexprs, stack, v)
	case *Expr:
	case *Var:
		mutate(&n.Xpr, stack, v)
	case *Param:
		mutate(&n.Xpr, stack, v)
	case *Aggref:
		mutate(&n.Xpr, stack, v)
		mutateList(n.Aggargtypes, stack, v)
		mutateList(n.Aggdirectargs, stack, v)
		mutateList(n.Args, stack, v)
		mutateList(n.Aggorder, stack, v)
		mutateList(n.Aggdistinct, stack, v)
		mutate(&n.Aggfilter, stack, v)
	case *GroupingFunc:
		mutate(&n.Xpr, stack, v)
		mutateList(n.Args, stack, v)
		mutateList(n.Refs, stack, v)
		mutateList(n.Cols, stack, v)
	case *WindowFunc:
		mutate(&n.Xpr, stack, v)
		mutateList(n.Args, stack, v)
		mutate(&n.Aggfilter, stack, v)
	case *SubscriptingRef:
		mutate(&n.Xpr, stack, v)
		mutateList(n.Refupperindexpr, stack, v)
		mutateList(n.Reflowerindexpr, stack, v)
		mutate(&n.Refexpr, stack, v)
		mutate(&n.Refassgnexpr, stack, v)
	case *FuncExpr:
		mutate(&n.Xpr, stack, v)
		mutateList(n.Args, stack, v)
	case *NamedArgExpr:
		mutate(&n.Xpr, stack, v)
		mutate(&n.Arg, stack, v)
	case *OpExpr:
		mutate(&n.Xpr, stack, v)
		mutateList(n.Args, stack, v)
	case *DistinctExpr:
		mutate(&n.Xpr, stack, v)
		mutateList(n.Args, stack, v)
	case *NullIfExpr:
		mutate(&n.Xpr, stack, v)
		mutateList(n.Args, stack, v)
	case *ScalarArrayOpExpr:
		mutate(&n.Xpr, stack, v)
		mutateList(n.Args, stack, v)
	case *BoolExpr:
		mutate(&n.Xpr, stack, v)
		mutateList(n.Args, stack, v)
	case *SubLink:
		mutate(&n.Xpr, stack, v)
		mutate(&n.Testexpr, stack, v)
		mutateList(n.OperName, stack, v)
		mutate(&n.Subselect, stack, v)
	case *SubPlan:
		mutate(&n.Xpr, stack, v)
		mutate(&n.Testexpr, stack, v)
		mutateList(n.ParamIds, stack, v)
		mutateList(n.SetParam, stack, v)
		mutateList(n.ParParam, stack, v)
		mutateList(n.Args, stack, v)
	case *AlternativeSubPlan:
		mutate(&n.Xpr, stack, v)
		mutateList(n.Subplans, stack, v)
	case *FieldSelect:
		mutate(&n.Xpr, stack, v)
		mutate(&n.Arg, stack, v)
	case *FieldStore:
		mutate(&n.Xpr, stack, v)
		mutate(&n.Arg, stack, v)
		mutateList(n.Newvals, stack, v)
		mutateList(n.Fieldnums, stack, v)
	case *RelabelType:
		mutate(&n.Xpr, stack, v)
		mutate(&n.Arg, stack, v)
	case *CoerceViaIo:
		mutate(&n.Xpr, stack, v)
		mutate(&n.Arg, stack, v)
	case *ArrayCoerceExpr:
		mutate(&n.Xpr, stack, v)
		mutate(&n.Arg, stack, v)
		mutate(&n.Elemexpr, stack, v)
	case *ConvertRowtypeExpr:
		mutate(&n.Xpr, stack, v)
		mutate(&n.Arg, stack, v)
	case *CollateExpr:
		mutate(&n.Xpr, stack, v)
		mutate(&n.Arg, stack, v)
	case *CaseExpr:
		mutate(&n.Xpr, stack, v)
		mutate(&n.Arg, stack, v)
		mutateList(n.Args, stack, v)
		mutate(&n.Defresult, stack, v)
	case *CaseWhen:
		mutate(&n.Xpr, stack, v)
		mutate(&n.Expr, stack, v)
		mutate(&n.Result, stack, v)
	case *CaseTestExpr:
		mutate(&n.Xpr, stack, v)
	case *ArrayExpr:
		mutate(&n.Xpr, stack, v)
		mutateList(n.Elements, stack, v)
	case *RowExpr:
		mutate(&n.Xpr, stack, v)
		mutateList(n.Args, stack, v)
		mutateList(n.Colnames, stack, v)
	case *RowCompareExpr:
		mutate(&n.Xpr, stack, v)
		mutateList(n.Opnos, stack, v)
		mutateList(n.Opfamilies, stack, v)
		mutateList(n.Inputcollids, stack, v)
		mutateList(n.Largs, stack, v)
		mutateList(n.Rargs, stack, v)
	case *CoalesceExpr:
		mutate(&n.Xpr, stack, v)
		mutateList(n.Args, stack, v)
	case *MinMaxExpr:
		mutate(&n.Xpr, stack, v)
		mutateList(n.Args, stack, v)
	case *SqlvalueFunction:
		mutate(&n.Xpr, stack, v)
	case *XmlExpr:
		mutate(&n.Xpr, stack, v)
		mutateList(n.NamedArgs, stack, v)
		mutateList(n.ArgNames, stack, v)
		mutateList(n.Args, stack, v)
	case *NullTest:
		mutate(&n.Xpr, stack, v)
		mutate(&n.Arg, stack, v)
	case *BooleanTest:
		mutate(&n.Xpr, stack, v)
		mutate(&n.Arg, stack, v)
	case *CoerceToDomain:
		mutate(&n.Xpr, stack, v)
		mutate(&n.Arg, stack, v)
	case *CoerceToDomainValue:
		mutate(&n.Xpr, stack, v)
	case *SetToDefault:
		mutate(&n.Xpr, stack, v)
	case *CurrentOfExpr:
		mutate(&n.Xpr, stack, v)
	case *NextValueExpr:
		mutate(&n.Xpr, stack, v)
	case *InferenceElem:
		mutate(&n.Xpr, stack, v)
		mutate(&n.Expr, stack, v)
	case *TargetEntry:
		mutate(&n.Xpr, stack, v)
		mutate(&n.Expr, stack, v)
	case *RangeTblRef:
	case *JoinExpr:
		mutate(&n.Larg, stack, v)
		mutate(&n.Rarg, stack, v)
		mutateList(n.UsingClause, stack, v)
		mutate(&n.Quals, stack, v)
		nodeWrapper = n.Alias
		mutate(&nodeWrapper, stack, v)
	case *FromExpr:
		mutateList(n.Fromlist, stack, v)
		mutate(&n.Quals, stack, v)
	case *OnConflictExpr:
		mutateList(n.ArbiterElems, stack, v)
		mutate(&n.ArbiterWhere, stack, v)
		mutateList(n.OnConflictSet, stack, v)
		mutate(&n.OnConflictWhere, stack, v)
		mutateList(n.ExclRelTlist, stack, v)
	case *IntoClause:
		nodeWrapper = n.Rel
		mutate(&nodeWrapper, stack, v)
		mutateList(n.ColNames, stack, v)
		mutateList(n.Options, stack, v)
		mutate(&n.ViewQuery, stack, v)
	case *RawStmt:
		mutate(&n.Stmt, stack, v)
	case *Query:
		mutate(&n.UtilityStmt, stack, v)
		mutateList(n.CteList, stack, v)
		mutateList(n.Rtable, stack, v)
		nodeWrapper = n.Jointree
		mutate(&nodeWrapper, stack, v)
		mutateList(n.TargetList, stack, v)
		nodeWrapper = n.OnConflict
		mutate(&nodeWrapper, stack, v)
		mutateList(n.ReturningList, stack, v)
		mutateList(n.GroupClause, stack, v)
		mutateList(n.GroupingSets, stack, v)
		mutate(&n.HavingQual, stack, v)
		mutateList(n.WindowClause, stack, v)
		mutateList(n.DistinctClause, stack, v)
		mutateList(n.SortClause, stack, v)
		mutate(&n.LimitOffset, stack, v)
		mutate(&n.LimitCount, stack, v)
		mutateList(n.RowMarks, stack, v)
		mutate(&n.SetOperations, stack, v)
		mutateList(n.ConstraintDeps, stack, v)
		mutateList(n.WithCheckOptions, stack, v)
	case *InsertStmt:
		nodeWrapper = n.Relation
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Cols, stack, v)
		mutate(&n.SelectStmt, stack, v)
		nodeWrapper = n.OnConflictClause
		mutate(&nodeWrapper, stack, v)
		mutateList(n.ReturningList, stack, v)
		nodeWrapper = n.WithClause
		mutate(&nodeWrapper, stack, v)
	case *DeleteStmt:
		nodeWrapper = n.Relation
		mutate(&nodeWrapper, stack, v)
		mutateList(n.UsingClause, stack, v)
		mutate(&n.WhereClause, stack, v)
		mutateList(n.ReturningList, stack, v)
		nodeWrapper = n.WithClause
		mutate(&nodeWrapper, stack, v)
	case *UpdateStmt:
		nodeWrapper = n.Relation
		mutate(&nodeWrapper, stack, v)
		mutateList(n.TargetList, stack, v)
		mutate(&n.WhereClause, stack, v)
		mutateList(n.FromClause, stack, v)
		mutateList(n.ReturningList, stack, v)
		nodeWrapper = n.WithClause
		mutate(&nodeWrapper, stack, v)
	case *SelectStmt:
		mutateList(n.DistinctClause, stack, v)
		nodeWrapper = n.IntoClause
		mutate(&nodeWrapper, stack, v)
		mutateList(n.TargetList, stack, v)
		mutateList(n.FromClause, stack, v)
		mutate(&n.WhereClause, stack, v)
		mutateList(n.GroupClause, stack, v)
		mutate(&n.HavingClause, stack, v)
		mutateList(n.WindowClause, stack, v)
		mutateList(n.ValuesLists, stack, v)
		mutateList(n.SortClause, stack, v)
		mutate(&n.LimitOffset, stack, v)
		mutate(&n.LimitCount, stack, v)
		mutateList(n.LockingClause, stack, v)
		nodeWrapper = n.WithClause
		mutate(&nodeWrapper, stack, v)
		nodeWrapper = n.Larg
		mutate(&nodeWrapper, stack, v)
		nodeWrapper = n.Rarg
		mutate(&nodeWrapper, stack, v)
	case *AlterTableStmt:
		nodeWrapper = n.Relation
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Cmds, stack, v)
	case *AlterTableCmd:
		nodeWrapper = n.Newowner
		mutate(&nodeWrapper, stack, v)
		mutate(&n.Def, stack, v)
	case *AlterDomainStmt:
		mutateList(n.TypeName, stack, v)
		mutate(&n.Def, stack, v)
	case *SetOperationStmt:
		mutate(&n.Larg, stack, v)
		mutate(&n.Rarg, stack, v)
		mutateList(n.ColTypes, stack, v)
		mutateList(n.ColTypmods, stack, v)
		mutateList(n.ColCollations, stack, v)
		mutateList(n.GroupClauses, stack, v)
	case *GrantStmt:
		mutateList(n.Objects, stack, v)
		mutateList(n.Privileges, stack, v)
		mutateList(n.Grantees, stack, v)
	case *GrantRoleStmt:
		mutateList(n.GrantedRoles, stack, v)
		mutateList(n.GranteeRoles, stack, v)
		nodeWrapper = n.Grantor
		mutate(&nodeWrapper, stack, v)
	case *AlterDefaultPrivilegesStmt:
		mutateList(n.Options, stack, v)
		nodeWrapper = n.Action
		mutate(&nodeWrapper, stack, v)
	case *ClosePortalStmt:
	case *ClusterStmt:
		nodeWrapper = n.Relation
		mutate(&nodeWrapper, stack, v)
	case *CopyStmt:
		nodeWrapper = n.Relation
		mutate(&nodeWrapper, stack, v)
		mutate(&n.Query, stack, v)
		mutateList(n.Attlist, stack, v)
		mutateList(n.Options, stack, v)
		mutate(&n.WhereClause, stack, v)
	case *CreateStmt:
		nodeWrapper = n.Relation
		mutate(&nodeWrapper, stack, v)
		mutateList(n.TableElts, stack, v)
		mutateList(n.InhRelations, stack, v)
		nodeWrapper = n.Partbound
		mutate(&nodeWrapper, stack, v)
		nodeWrapper = n.Partspec
		mutate(&nodeWrapper, stack, v)
		nodeWrapper = n.OfTypename
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Constraints, stack, v)
		mutateList(n.Options, stack, v)
	case *DefineStmt:
		mutateList(n.Defnames, stack, v)
		mutateList(n.Args, stack, v)
		mutateList(n.Definition, stack, v)
	case *DropStmt:
		mutateList(n.Objects, stack, v)
	case *TruncateStmt:
		mutateList(n.Relations, stack, v)
	case *CommentStmt:
		mutate(&n.Object, stack, v)
	case *FetchStmt:
	case *IndexStmt:
		nodeWrapper = n.Relation
		mutate(&nodeWrapper, stack, v)
		mutateList(n.IndexParams, stack, v)
		mutateList(n.IndexIncludingParams, stack, v)
		mutateList(n.Options, stack, v)
		mutate(&n.WhereClause, stack, v)
		mutateList(n.ExcludeOpNames, stack, v)
	case *CreateFunctionStmt:
		mutateList(n.Funcname, stack, v)
		mutateList(n.Parameters, stack, v)
		nodeWrapper = n.ReturnType
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Options, stack, v)
	case *AlterFunctionStmt:
		nodeWrapper = n.Func
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Actions, stack, v)
	case *DoStmt:
		mutateList(n.Args, stack, v)
	case *RenameStmt:
		nodeWrapper = n.Relation
		mutate(&nodeWrapper, stack, v)
		mutate(&n.Object, stack, v)
	case *RuleStmt:
		nodeWrapper = n.Relation
		mutate(&nodeWrapper, stack, v)
		mutate(&n.WhereClause, stack, v)
		mutateList(n.Actions, stack, v)
	case *NotifyStmt:
	case *ListenStmt:
	case *UnlistenStmt:
	case *TransactionStmt:
		mutateList(n.Options, stack, v)
	case *ViewStmt:
		nodeWrapper = n.View
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Aliases, stack, v)
		mutate(&n.Query, stack, v)
		mutateList(n.Options, stack, v)
	case *LoadStmt:
	case *CreateDomainStmt:
		mutateList(n.Domainname, stack, v)
		nodeWrapper = n.TypeName
		mutate(&nodeWrapper, stack, v)
		nodeWrapper = n.CollClause
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Constraints, stack, v)
	case *CreatedbStmt:
		mutateList(n.Options, stack, v)
	case *DropdbStmt:
	case *VacuumStmt:
		mutateList(n.Options, stack, v)
		mutateList(n.Rels, stack, v)
	case *ExplainStmt:
		mutate(&n.Query, stack, v)
		mutateList(n.Options, stack, v)
	case *CreateTableAsStmt:
		mutate(&n.Query, stack, v)
		nodeWrapper = n.Into
		mutate(&nodeWrapper, stack, v)
	case *CreateSeqStmt:
		nodeWrapper = n.Sequence
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Options, stack, v)
	case *AlterSeqStmt:
		nodeWrapper = n.Sequence
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Options, stack, v)
	case *VariableSetStmt:
		mutateList(n.Args, stack, v)
	case *VariableShowStmt:
	case *DiscardStmt:
	case *CreateTrigStmt:
		nodeWrapper = n.Relation
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Funcname, stack, v)
		mutateList(n.Args, stack, v)
		mutateList(n.Columns, stack, v)
		mutate(&n.WhenClause, stack, v)
		mutateList(n.TransitionRels, stack, v)
		nodeWrapper = n.Constrrel
		mutate(&nodeWrapper, stack, v)
	case *CreatePlangStmt:
		mutateList(n.Plhandler, stack, v)
		mutateList(n.Plinline, stack, v)
		mutateList(n.Plvalidator, stack, v)
	case *CreateRoleStmt:
		mutateList(n.Options, stack, v)
	case *AlterRoleStmt:
		nodeWrapper = n.Role
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Options, stack, v)
	case *DropRoleStmt:
		mutateList(n.Roles, stack, v)
	case *LockStmt:
		mutateList(n.Relations, stack, v)
	case *ConstraintsSetStmt:
		mutateList(n.Constraints, stack, v)
	case *ReindexStmt:
		nodeWrapper = n.Relation
		mutate(&nodeWrapper, stack, v)
	case *CheckPointStmt:
	case *CreateSchemaStmt:
		nodeWrapper = n.Authrole
		mutate(&nodeWrapper, stack, v)
		mutateList(n.SchemaElts, stack, v)
	case *AlterDatabaseStmt:
		mutateList(n.Options, stack, v)
	case *AlterDatabaseSetStmt:
		nodeWrapper = n.Setstmt
		mutate(&nodeWrapper, stack, v)
	case *AlterRoleSetStmt:
		nodeWrapper = n.Role
		mutate(&nodeWrapper, stack, v)
		nodeWrapper = n.Setstmt
		mutate(&nodeWrapper, stack, v)
	case *CreateConversionStmt:
		mutateList(n.ConversionName, stack, v)
		mutateList(n.FuncName, stack, v)
	case *CreateCastStmt:
		nodeWrapper = n.Sourcetype
		mutate(&nodeWrapper, stack, v)
		nodeWrapper = n.Targettype
		mutate(&nodeWrapper, stack, v)
		nodeWrapper = n.Func
		mutate(&nodeWrapper, stack, v)
	case *CreateOpClassStmt:
		mutateList(n.Opclassname, stack, v)
		mutateList(n.Opfamilyname, stack, v)
		nodeWrapper = n.Datatype
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Items, stack, v)
	case *CreateOpFamilyStmt:
		mutateList(n.Opfamilyname, stack, v)
	case *AlterOpFamilyStmt:
		mutateList(n.Opfamilyname, stack, v)
		mutateList(n.Items, stack, v)
	case *PrepareStmt:
		mutateList(n.Argtypes, stack, v)
		mutate(&n.Query, stack, v)
	case *ExecuteStmt:
		mutateList(n.Params, stack, v)
	case *DeallocateStmt:
	case *DeclareCursorStmt:
		mutate(&n.Query, stack, v)
	case *CreateTableSpaceStmt:
		nodeWrapper = n.Owner
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Options, stack, v)
	case *DropTableSpaceStmt:
	case *AlterObjectDependsStmt:
		nodeWrapper = n.Relation
		mutate(&nodeWrapper, stack, v)
		mutate(&n.Object, stack, v)
		mutate(&n.Extname, stack, v)
	case *AlterObjectSchemaStmt:
		nodeWrapper = n.Relation
		mutate(&nodeWrapper, stack, v)
		mutate(&n.Object, stack, v)
	case *AlterOwnerStmt:
		nodeWrapper = n.Relation
		mutate(&nodeWrapper, stack, v)
		mutate(&n.Object, stack, v)
		nodeWrapper = n.Newowner
		mutate(&nodeWrapper, stack, v)
	case *AlterOperatorStmt:
		nodeWrapper = n.Opername
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Options, stack, v)
	case *DropOwnedStmt:
		mutateList(n.Roles, stack, v)
	case *ReassignOwnedStmt:
		mutateList(n.Roles, stack, v)
		nodeWrapper = n.Newrole
		mutate(&nodeWrapper, stack, v)
	case *CompositeTypeStmt:
		nodeWrapper = n.Typevar
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Coldeflist, stack, v)
	case *CreateEnumStmt:
		mutateList(n.TypeName, stack, v)
		mutateList(n.Vals, stack, v)
	case *CreateRangeStmt:
		mutateList(n.TypeName, stack, v)
		mutateList(n.Params, stack, v)
	case *AlterEnumStmt:
		mutateList(n.TypeName, stack, v)
	case *AlterTsdictionaryStmt:
		mutateList(n.Dictname, stack, v)
		mutateList(n.Options, stack, v)
	case *AlterTsconfigurationStmt:
		mutateList(n.Cfgname, stack, v)
		mutateList(n.Tokentype, stack, v)
		mutateList(n.Dicts, stack, v)
	case *CreateFdwStmt:
		mutateList(n.FuncOptions, stack, v)
		mutateList(n.Options, stack, v)
	case *AlterFdwStmt:
		mutateList(n.FuncOptions, stack, v)
		mutateList(n.Options, stack, v)
	case *CreateForeignServerStmt:
		mutateList(n.Options, stack, v)
	case *AlterForeignServerStmt:
		mutateList(n.Options, stack, v)
	case *CreateUserMappingStmt:
		nodeWrapper = n.User
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Options, stack, v)
	case *AlterUserMappingStmt:
		nodeWrapper = n.User
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Options, stack, v)
	case *DropUserMappingStmt:
		nodeWrapper = n.User
		mutate(&nodeWrapper, stack, v)
	case *AlterTableSpaceOptionsStmt:
		mutateList(n.Options, stack, v)
	case *AlterTableMoveAllStmt:
		mutateList(n.Roles, stack, v)
	case *SecLabelStmt:
		mutate(&n.Object, stack, v)
	case *CreateForeignTableStmt:
		nodeWrapper = n.Base
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Options, stack, v)
	case *ImportForeignSchemaStmt:
		mutateList(n.TableList, stack, v)
		mutateList(n.Options, stack, v)
	case *CreateExtensionStmt:
		mutateList(n.Options, stack, v)
	case *AlterExtensionStmt:
		mutateList(n.Options, stack, v)
	case *AlterExtensionContentsStmt:
		mutate(&n.Object, stack, v)
	case *CreateEventTrigStmt:
		mutateList(n.Whenclause, stack, v)
		mutateList(n.Funcname, stack, v)
	case *AlterEventTrigStmt:
	case *RefreshMatViewStmt:
		nodeWrapper = n.Relation
		mutate(&nodeWrapper, stack, v)
	case *ReplicaIdentityStmt:
	case *AlterSystemStmt:
		nodeWrapper = n.Setstmt
		mutate(&nodeWrapper, stack, v)
	case *CreatePolicyStmt:
		nodeWrapper = n.Table
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Roles, stack, v)
		mutate(&n.Qual, stack, v)
		mutate(&n.WithCheck, stack, v)
	case *AlterPolicyStmt:
		nodeWrapper = n.Table
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Roles, stack, v)
		mutate(&n.Qual, stack, v)
		mutate(&n.WithCheck, stack, v)
	case *CreateTransformStmt:
		nodeWrapper = n.TypeName
		mutate(&nodeWrapper, stack, v)
		nodeWrapper = n.Fromsql
		mutate(&nodeWrapper, stack, v)
		nodeWrapper = n.Tosql
		mutate(&nodeWrapper, stack, v)
	case *CreateAmStmt:
		mutateList(n.HandlerName, stack, v)
	case *CreatePublicationStmt:
		mutateList(n.Options, stack, v)
		mutateList(n.Tables, stack, v)
	case *AlterPublicationStmt:
		mutateList(n.Options, stack, v)
		mutateList(n.Tables, stack, v)
	case *CreateSubscriptionStmt:
		mutateList(n.Publication, stack, v)
		mutateList(n.Options, stack, v)
	case *AlterSubscriptionStmt:
		mutateList(n.Publication, stack, v)
		mutateList(n.Options, stack, v)
	case *DropSubscriptionStmt:
	case *CreateStatsStmt:
		mutateList(n.Defnames, stack, v)
		mutateList(n.StatTypes, stack, v)
		mutateList(n.Exprs, stack, v)
		mutateList(n.Relations, stack, v)
	case *AlterCollationStmt:
		mutateList(n.Collname, stack, v)
	case *CallStmt:
		nodeWrapper = n.Funccall
		mutate(&nodeWrapper, stack, v)
		nodeWrapper = n.Funcexpr
		mutate(&nodeWrapper, stack, v)
	case *AExpr:
		mutateList(n.Name, stack, v)
		mutate(&n.Lexpr, stack, v)
		mutate(&n.Rexpr, stack, v)
	case *ColumnRef:
		mutateList(n.Fields, stack, v)
	case *ParamRef:
	case *AConst:
		mutate(&n.Val, stack, v)
	case *FuncCall:
		mutateList(n.Funcname, stack, v)
		mutateList(n.Args, stack, v)
		mutateList(n.AggOrder, stack, v)
		mutate(&n.AggFilter, stack, v)
		nodeWrapper = n.Over
		mutate(&nodeWrapper, stack, v)
	case *AStar:
	case *AIndices:
		mutate(&n.Lidx, stack, v)
		mutate(&n.Uidx, stack, v)
	case *AIndirection:
		mutate(&n.Arg, stack, v)
		mutateList(n.Indirection, stack, v)
	case *AArrayExpr:
		mutateList(n.Elements, stack, v)
	case *ResTarget:
		mutateList(n.Indirection, stack, v)
		mutate(&n.Val, stack, v)
	case *MultiAssignRef:
		mutate(&n.Source, stack, v)
	case *TypeCast:
		mutate(&n.Arg, stack, v)
		nodeWrapper = n.TypeName
		mutate(&nodeWrapper, stack, v)
	case *CollateClause:
		mutate(&n.Arg, stack, v)
		mutateList(n.Collname, stack, v)
	case *SortBy:
		mutate(&n.Node, stack, v)
		mutateList(n.UseOp, stack, v)
	case *WindowDef:
		mutateList(n.PartitionClause, stack, v)
		mutateList(n.OrderClause, stack, v)
		mutate(&n.StartOffset, stack, v)
		mutate(&n.EndOffset, stack, v)
	case *RangeSubselect:
		mutate(&n.Subquery, stack, v)
		nodeWrapper = n.Alias
		mutate(&nodeWrapper, stack, v)
	case *RangeFunction:
		mutateList(n.Functions, stack, v)
		nodeWrapper = n.Alias
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Coldeflist, stack, v)
	case *RangeTableSample:
		mutate(&n.Relation, stack, v)
		mutateList(n.Method, stack, v)
		mutateList(n.Args, stack, v)
		mutate(&n.Repeatable, stack, v)
	case *RangeTableFunc:
		mutate(&n.Docexpr, stack, v)
		mutate(&n.Rowexpr, stack, v)
		mutateList(n.Namespaces, stack, v)
		mutateList(n.Columns, stack, v)
		nodeWrapper = n.Alias
		mutate(&nodeWrapper, stack, v)
	case *RangeTableFuncCol:
		nodeWrapper = n.TypeName
		mutate(&nodeWrapper, stack, v)
		mutate(&n.Colexpr, stack, v)
		mutate(&n.Coldefexpr, stack, v)
	case *TypeName:
		mutateList(n.Names, stack, v)
		mutateList(n.Typmods, stack, v)
		mutateList(n.ArrayBounds, stack, v)
	case *ColumnDef:
		nodeWrapper = n.TypeName
		mutate(&nodeWrapper, stack, v)
		mutate(&n.RawDefault, stack, v)
		mutate(&n.CookedDefault, stack, v)
		nodeWrapper = n.IdentitySequence
		mutate(&nodeWrapper, stack, v)
		nodeWrapper = n.CollClause
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Constraints, stack, v)
		mutateList(n.Fdwoptions, stack, v)
	case *IndexElem:
		mutate(&n.Expr, stack, v)
		mutateList(n.Collation, stack, v)
		mutateList(n.Opclass, stack, v)
	case *Constraint:
		mutate(&n.RawExpr, stack, v)
		mutateList(n.Keys, stack, v)
		mutateList(n.Including, stack, v)
		mutateList(n.Exclusions, stack, v)
		mutateList(n.Options, stack, v)
		mutate(&n.WhereClause, stack, v)
		nodeWrapper = n.Pktable
		mutate(&nodeWrapper, stack, v)
		mutateList(n.FkAttrs, stack, v)
		mutateList(n.PkAttrs, stack, v)
		mutateList(n.OldConpfeqop, stack, v)
	case *DefElem:
		mutate(&n.Arg, stack, v)
	case *RangeTblEntry:
		nodeWrapper = n.Tablesample
		mutate(&nodeWrapper, stack, v)
		nodeWrapper = n.Subquery
		mutate(&nodeWrapper, stack, v)
		mutateList(n.Joinaliasvars, stack, v)
		mutateList(n.Functions, stack, v)
		nodeWrapper = n.Tablefunc
		mutate(&nodeWrapper, stack, v)
		mutateList(n.ValuesLists, stack, v)
		mutateList(n.Coltypes, stack, v)
		mutateList(n.Coltypmods, stack, v)
		mutateList(n.Colcollations, stack, v)
		nodeWrapper = n.Alias
		mutate(&nodeWrapper, stack, v)
		nodeWrapper = n.Eref
		mutate(&nodeWrapper, stack, v)
		mutateList(n.SecurityQuals, stack, v)
	case *RangeTblFunction:
		mutate(&n.Funcexpr, stack, v)
		mutateList(n.Funccolnames, stack, v)
		mutateList(n.Funccoltypes, stack, v)
		mutateList(n.Funccoltypmods, stack, v)
		mutateList(n.Funccolcollations, stack, v)
	case *TableSampleClause:
		mutateList(n.Args, stack, v)
		mutate(&n.Repeatable, stack, v)
	case *WithCheckOption:
		mutate(&n.Qual, stack, v)
	case *SortGroupClause:
	case *GroupingSet:
		mutateList(n.Content, stack, v)
	case *WindowClause:
		mutateList(n.PartitionClause, stack, v)
		mutateList(n.OrderClause, stack, v)
		mutate(&n.StartOffset, stack, v)
		mutate(&n.EndOffset, stack, v)
	case *ObjectWithArgs:
		mutateList(n.Objname, stack, v)
		mutateList(n.Objargs, stack, v)
	case *AccessPriv:
		mutateList(n.Cols, stack, v)
	case *CreateOpClassItem:
		nodeWrapper = n.Name
		mutate(&nodeWrapper, stack, v)
		mutateList(n.OrderFamily, stack, v)
		mutateList(n.ClassArgs, stack, v)
		nodeWrapper = n.Storedtype
		mutate(&nodeWrapper, stack, v)
	case *TableLikeClause:
		nodeWrapper = n.Relation
		mutate(&nodeWrapper, stack, v)
	case *FunctionParameter:
		nodeWrapper = n.ArgType
		mutate(&nodeWrapper, stack, v)
		mutate(&n.Defexpr, stack, v)
	case *LockingClause:
		mutateList(n.LockedRels, stack, v)
	case *RowMarkClause:
	case *XmlSerialize:
		mutate(&n.Expr, stack, v)
		nodeWrapper = n.TypeName
		mutate(&nodeWrapper, stack, v)
	case *WithClause:
		mutateList(n.Ctes, stack, v)
	case *InferClause:
		mutateList(n.IndexElems, stack, v)
		mutate(&n.WhereClause, stack, v)
	case *OnConflictClause:
		nodeWrapper = n.Infer
		mutate(&nodeWrapper, stack, v)
		mutateList(n.TargetList, stack, v)
		mutate(&n.WhereClause, stack, v)
	case *CommonTableExpr:
		mutateList(n.Aliascolnames, stack, v)
		mutate(&n.Ctequery, stack, v)
		mutateList(n.Ctecolnames, stack, v)
		mutateList(n.Ctecoltypes, stack, v)
		mutateList(n.Ctecoltypmods, stack, v)
		mutateList(n.Ctecolcollations, stack, v)
	case *RoleSpec:
	case *TriggerTransition:
	case *PartitionElem:
		mutate(&n.Expr, stack, v)
		mutateList(n.Collation, stack, v)
		mutateList(n.Opclass, stack, v)
	case *PartitionSpec:
		mutateList(n.PartParams, stack, v)
	case *PartitionBoundSpec:
		mutateList(n.Listdatums, stack, v)
		mutateList(n.Lowerdatums, stack, v)
		mutateList(n.Upperdatums, stack, v)
	case *PartitionRangeDatum:
		mutate(&n.Value, stack, v)
	case *PartitionCmd:
		nodeWrapper = n.Name
		mutate(&nodeWrapper, stack, v)
		nodeWrapper = n.Bound
		mutate(&nodeWrapper, stack, v)
	case *VacuumRelation:
		nodeWrapper = n.Relation
		mutate(&nodeWrapper, stack, v)
		mutateList(n.VaCols, stack, v)
	case *InlineCodeBlock:
	case *CallContext:
	case *Root:
		mutate(&n.Node, stack, v)
	case Nodes:
		mutateList(n, stack, v)
	}
}
